model: resnet50
pretrained: true
num_classes: 1604
img_size: 224
batch_size: 512


apex_amp: true

hflip: 0.5
vflip: 0.5
scale: [0.8, 1.0]
color_jitter: 0.2

lr: 0.01
epochs: 100
sched: plateau
patience_epochs: 1
decay_rate: 0.5

eval_metric: loss